In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm
#from numpy import genfromtxt
#import collections
#import seaborn as sns
from sklearn import linear_model
#from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
#reading the given data set
df = pd.read_csv('data.csv')

In [3]:
#if possible try to do it with for loop
#df['X(K-5)']=[0 for i in range(len(df))]
#df['X(K-5)'][5:]=df['X'][:len(df)-5]

In [4]:
#Previous four historical values
#using pandas inbuild shift method to get the desired past historical values
df['X(k-1)'] = df['X'].shift(1)
df['X(k-2)'] = df['X'].shift(2)
df['X(k-3)'] = df['X'].shift(3)
df['X(k-4)'] = df['X'].shift(4)
df['Y(k-1)'] = df['Y'].shift(1)
df['Y(k-2)'] = df['Y'].shift(2)
df['Y(k-3)'] = df['Y'].shift(3)
df['Y(k-4)'] = df['Y'].shift(4)

In [5]:
#printing first 10 values
df.head(10)

X       Y   X(k-1)   X(k-2)   X(k-3)   X(k-4)  Y(k-1)  Y(k-2)  \
0   9.8915  6.0095      NaN      NaN      NaN      NaN     NaN     NaN   
1  10.4510  5.5741   9.8915      NaN      NaN      NaN  6.0095     NaN   
2  10.0460  6.1149  10.4510   9.8915      NaN      NaN  5.5741  6.0095   
3  10.9780  6.0194  10.0460  10.4510   9.8915      NaN  6.1149  5.5741   
4  10.6910  6.0317  10.9780  10.0460  10.4510   9.8915  6.0194  6.1149   
5  10.8250  6.1201  10.6910  10.9780  10.0460  10.4510  6.0317  6.0194   
6  10.9660  5.9217  10.8250  10.6910  10.9780  10.0460  6.1201  6.0317   
7  10.9000  6.0420  10.9660  10.8250  10.6910  10.9780  5.9217  6.1201   
8  10.4290  6.2682  10.9000  10.9660  10.8250  10.6910  6.0420  5.9217   
9  10.0950  5.9239  10.4290  10.9000  10.9660  10.8250  6.2682  6.0420   

   Y(k-3)  Y(k-4)  
0     NaN     NaN  
1     NaN     NaN  
2     NaN     NaN  
3  6.0095     NaN  
4  5.5741  6.0095  
5  6.1149  5.5741  
6  6.0194  6.1149  
7  6.0317  6.0194  
8  6.1201  6.0317  
9  5.9217  6.1201

In [6]:
#changing all the nan value to 0
df = df.fillna(0)

In [7]:
#checking if the values are filled or not
df.head()

X       Y   X(k-1)   X(k-2)   X(k-3)  X(k-4)  Y(k-1)  Y(k-2)  Y(k-3)  \
0   9.8915  6.0095   0.0000   0.0000   0.0000  0.0000  0.0000  0.0000  0.0000   
1  10.4510  5.5741   9.8915   0.0000   0.0000  0.0000  6.0095  0.0000  0.0000   
2  10.0460  6.1149  10.4510   9.8915   0.0000  0.0000  5.5741  6.0095  0.0000   
3  10.9780  6.0194  10.0460  10.4510   9.8915  0.0000  6.1149  5.5741  6.0095   
4  10.6910  6.0317  10.9780  10.0460  10.4510  9.8915  6.0194  6.1149  5.5741   

   Y(k-4)  
0  0.0000  
1  0.0000  
2  0.0000  
3  0.0000  
4  6.0095

In [8]:
#dividing data into train and test
df_train=df[:1500]
df_test=df[1500:2000]

In [9]:
#check if all the data is in float datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X       2000 non-null   float64
 1   Y       2000 non-null   float64
 2   X(k-1)  2000 non-null   float64
 3   X(k-2)  2000 non-null   float64
 4   X(k-3)  2000 non-null   float64
 5   X(k-4)  2000 non-null   float64
 6   Y(k-1)  2000 non-null   float64
 7   Y(k-2)  2000 non-null   float64
 8   Y(k-3)  2000 non-null   float64
 9   Y(k-4)  2000 non-null   float64
dtypes: float64(10)
memory usage: 156.4 KB


In [10]:
#X output for 1st question
Y=df_train[['X']]
Y

X
0      9.8915
1     10.4510
2     10.0460
3     10.9780
4     10.6910
...       ...
1495   9.8036
1496   9.9767
1497   9.6262
1498   9.6386
1499  10.1690

[1500 rows x 1 columns]

In [11]:
# traning past four historical values
new_X=df_train[['X(k-1)','X(k-2)','X(k-3)','X(k-4)']]
new_X.head()

X(k-1)   X(k-2)   X(k-3)  X(k-4)
0   0.0000   0.0000   0.0000  0.0000
1   9.8915   0.0000   0.0000  0.0000
2  10.4510   9.8915   0.0000  0.0000
3  10.0460  10.4510   9.8915  0.0000
4  10.9780  10.0460  10.4510  9.8915

In [12]:
#Question 1
#with sklearn
regr = linear_model.LinearRegression()
regr.fit(new_X, Y)
print('Sklearn Linear regression output:')
print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Sklearn Linear regression output:
Intercept: 
 [1.38981954]
Coefficients: 
 [[ 0.77524581  0.13401239  0.03140849 -0.07605579]]


$ a_1 = 0.77524581, a_2 = 0.13401239, a_3 = 0.03140849, a_4 = -0.07605579, b = 1.38981954 $ 

In [13]:
x_pred_train = regr.predict(new_X)
print('Train error',mean_squared_error( Y,x_pred_train))

Train error 0.1538497174278458


Since the Train error = 15%, the model is underfitted

In [14]:
#Question 2 Starts from here
#testing past four historical values
X_test=df_test[['X(k-1)','X(k-2)','X(k-3)','X(k-4)']]
X_test.head()

X(k-1)   X(k-2)   X(k-3)   X(k-4)
1500  10.1690   9.6386   9.6262   9.9767
1501   9.9483  10.1690   9.6386   9.6262
1502   9.9490   9.9483  10.1690   9.6386
1503  10.0680   9.9490   9.9483  10.1690
1504   9.6956  10.0680   9.9490   9.9483

In [15]:
#sklearn prediction
predictions = regr.predict(X_test) 
print(predictions[:10])

[[10.10854462]
 [10.03557506]
 [10.02225717]
 [10.06733338]
 [ 9.81138682]
 [10.15077224]
 [10.16877399]
 [10.57768756]
 [10.61350405]
 [10.44626584]]


In [16]:
#Question 2 Model Evaluation and disscusing the accuuracy of the model
from sklearn import metrics
y_test=df['X'][1500:]
meanAbErr = metrics.mean_absolute_error(y_test, predictions)
meanSqErr = metrics.mean_squared_error(y_test, predictions)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, predictions))
print('Evaluvation of YX using sklearn:')
print('R squared: {:.2f}'.format(regr.score(new_X,Y)*100))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

Evaluvation of YX using sklearn:
R squared: 81.25
Mean Absolute Error: 0.2733641270933175
Mean Square Error: 0.11863856845706473
Root Mean Square Error: 0.34443949897923254


In [17]:
#Question 3
#for both X and Y
#immediate historical values
X_k_train=df_train[['X(k-1)','X(k-2)','Y(k-1)','Y(k-2)']]
X_k=df_train[['X']]
Y_k_train=df_train[['Y(k-1)','Y(k-2)','X(k-1)','X(k-2)']]
Y_k=df_train[['Y']]

In [18]:
X_k_test=df_test[['X(k-1)','X(k-2)','Y(k-1)','Y(k-2)']]
X_Test=df_test[['X']]
Y_k_test=df_test[['Y(k-1)','Y(k-2)','X(k-1)','X(k-2)']]
Y_Test=df_test[['Y']]

In [19]:
#Question 3
# with sklearn
#Find X
regr_X = linear_model.LinearRegression()
regr_X.fit(X_k_train, X_k)
print('Sklearn Linear regression output of X:')
print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Sklearn Linear regression output of X:
Intercept: 
 [1.38981954]
Coefficients: 
 [[ 0.77524581  0.13401239  0.03140849 -0.07605579]]


In [20]:
#Find Y
regr = linear_model.LinearRegression()
regr.fit(Y_k_train, Y_k)
print('Sklearn Linear regression output of Y:')
print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Sklearn Linear regression output of Y:
Intercept: 
 [2.91583521]
Coefficients: 
 [[ 0.44228597  0.10381613 -0.00409023 -0.02737421]]


In [21]:
#sklearn prediction of X
predict_X = regr_X.predict(X_k_test) 
print(predict_X[:10])

[[ 9.98793115]
 [ 9.93003977]
 [ 9.95724394]
 [10.03288501]
 [ 9.75633361]
 [10.15280887]
 [10.18326994]
 [10.49629042]
 [10.58747821]
 [10.44739021]]


In [22]:
#Model Evaluation for X and Y
meanAbErr = metrics.mean_absolute_error(X_Test, predict_X)
meanSqErr = metrics.mean_squared_error(X_Test, predict_X)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(X_Test, predict_X))
print('Evaluvation of X:')
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

Evaluvation of X:
Mean Absolute Error: 0.26756607184147235
Mean Square Error: 0.11665862816363735
Root Mean Square Error: 0.3415532581657469


In [23]:
#sklearn prediction of Y
predict_Y = regr.predict(Y_k_test) 
print(predict_Y[:10])

[[6.02479847]
 [5.84595043]
 [5.77676296]
 [5.90449796]
 [5.76845441]
 [5.65330568]
 [5.77097838]
 [5.79358161]
 [5.6807355 ]
 [5.59975747]]


In [24]:
#Evaluate Y
meanAbErr = metrics.mean_absolute_error(Y_Test, predict_Y)
meanSqErr = metrics.mean_squared_error(Y_Test, predict_Y)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(Y_Test, predict_Y))
print('Evaluvation of Y:')
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

Evaluvation of Y:
Mean Absolute Error: 0.25890676132481444
Mean Square Error: 0.10471547027402772
Root Mean Square Error: 0.32359769819024936
